# Generated by Django 3.1.4 on 2021-04-26 06:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffle',
            name='slot',
        ),
        migrations.AddField(
            model_name='raffle',
            name='slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], size=24),
        ),
    ]
