# Generated by Django 3.1.4 on 2021-04-26 06:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_auto_20210426_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=list, size=24),
        ),
    ]
