# Generated by Django 3.1.4 on 2021-04-26 14:06

import django.contrib.postgres.fields
from django.db import migrations, models
import raffles.models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_auto_20210426_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=True), default=raffles.models.get_raffle_default, size=24),
        ),
    ]
