# Generated by Django 3.1.4 on 2021-04-26 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('paid_total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_total_final_price', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('detail_address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('merchant_uid', models.CharField(blank=True, max_length=100, unique=True)),
                ('order_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('I', '결제대기'), ('P', '결제완료'), ('R', '배송준비중'), ('C', '주문취소'), ('S', '배송중'), ('D', '배송완료')], default='I', max_length=1)),
                ('message', models.CharField(choices=[('D', '문앞에 두고 가세요'), ('C', '배송전에 연락바랍니다'), ('H', '빨리 와주세요 현기증 난단 말이에요')], default='H', max_length=1)),
                ('paid_total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_total_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_shipping_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_total', models.PositiveIntegerField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliverycompany')),
                ('items', models.ManyToManyField(to='core.OrderItem')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
