# Generated by Django 3.1.4 on 2021-04-26 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210426_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=True), size=None),
        ),
    ]
