# Generated by Django 3.1.4 on 2021-04-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210426_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merchant_uid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_shipping_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_total_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='password',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='paid_total_final_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='paid_total_price',
        ),
        migrations.DeleteModel(
            name='DeliveryCompany',
        ),
    ]
