# Generated by Django 3.1.4 on 2021-04-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210428_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_total',
            new_name='paid_value',
        ),
    ]
