# Generated by Django 3.1.4 on 2021-04-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210428_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1a',
            new_name='address_line_1',
        ),
    ]
