# Generated by Django 3.1.4 on 2021-01-06 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0002_auto_20210106_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='slot',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
