# Generated by Django 3.1.4 on 2021-04-26 08:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0003_auto_20210106_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='slot',
        ),
        migrations.AddField(
            model_name='break',
            name='slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=list, size=12),
        ),
    ]
