# Generated by Django 3.1.4 on 2021-04-26 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0005_auto_20210426_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=True), blank=True, default=list, size=12),
        ),
    ]
