# Generated by Django 3.1.4 on 2021-04-26 14:06

import breaks.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0007_auto_20210426_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=True), default=breaks.models.get_break_default, size=12),
        ),
    ]
